local M = {}

function M.get(t, _opts)
  return {
    AerialNormal = { fg = t.fg, bg = t.bg_sidebar },
    AerialCursorLine = { bg = t.bg_selection },
    AerialLine = { bg = t.bg_selection },
    AerialLineNC = { bg = t.bg_cursorline },
    AerialGuide = { fg = t.border },
    AerialTextIcon = { fg = t.fg },
    AerialFunctionIcon = { fg = t.blue },
    AerialClassIcon = { fg = t.violet },
    AerialMethodIcon = { fg = t.blue },
    AerialConstructorIcon = { fg = t.violet },
    AerialFieldIcon = { fg = t.fg },
    AerialVariableIcon = { fg = t.fg },
    AerialInterfaceIcon = { fg = t.violet },
    AerialModuleIcon = { fg = t.fg },
    AerialPropertyIcon = { fg = t.fg },
    AerialUnitIcon = { fg = t.orange },
    AerialValueIcon = { fg = t.orange },
    AerialEnumIcon = { fg = t.violet },
    AerialKeywordIcon = { fg = t.green },
    AerialSnippetIcon = { fg = t.violet },
    AerialColorIcon = { fg = t.gold },
    AerialFileIcon = { fg = t.blue },
    AerialReferenceIcon = { fg = t.teal },
    AerialFolderIcon = { fg = t.blue },
    AerialEnumMemberIcon = { fg = t.orange },
    AerialConstantIcon = { fg = t.orange },
    AerialStructIcon = { fg = t.violet },
    AerialEventIcon = { fg = t.orange },
    AerialOperatorIcon = { fg = t.teal },
    AerialTypeParameterIcon = { fg = t.violet },
    AerialText = { fg = t.fg },
    AerialFunction = { fg = t.blue },
    AerialClass = { fg = t.violet },
    AerialMethod = { fg = t.blue },
    AerialConstructor = { fg = t.violet },
    AerialField = { fg = t.fg },
    AerialVariable = { fg = t.fg },
    AerialInterface = { fg = t.violet },
    AerialModule = { fg = t.fg },
    AerialProperty = { fg = t.fg },
    AerialEnum = { fg = t.violet },
    AerialKeyword = { fg = t.green },
    AerialConstant = { fg = t.orange },
    AerialStruct = { fg = t.violet },
    AerialOperator = { fg = t.teal },
  }
end

return M
