local M = {}

function M.get(t, _opts)
  return {
    BufferLineFill = { bg = t.bg_dark },
    BufferLineBackground = { fg = t.fg_dim, bg = t.bg_dark },
    BufferLineTab = { fg = t.fg_dim, bg = t.bg_dark },
    BufferLineTabSelected = { fg = t.green, bg = t.bg, bold = true },
    BufferLineTabClose = { fg = t.fg_gutter, bg = t.bg_dark },
    BufferLineTabSeparator = { fg = t.border, bg = t.bg_dark },
    BufferLineTabSeparatorSelected = { fg = t.green, bg = t.bg },
    BufferLineBuffer = { fg = t.fg_dim, bg = t.bg_dark },
    BufferLineBufferSelected = { fg = t.green, bg = t.bg, bold = true },
    BufferLineBufferVisible = { fg = t.fg, bg = t.bg_statusline },
    BufferLineIndicatorSelected = { fg = t.green, bg = t.bg },
    BufferLineIndicatorVisible = { fg = t.border, bg = t.bg_statusline },
    BufferLineModified = { fg = t.warn, bg = t.bg_dark },
    BufferLineModifiedSelected = { fg = t.green, bg = t.bg },
    BufferLineModifiedVisible = { fg = t.warn, bg = t.bg_statusline },
    BufferLineError = { fg = t.error, bg = t.bg_dark },
    BufferLineErrorSelected = { fg = t.error, bg = t.bg },
    BufferLineErrorVisible = { fg = t.error, bg = t.bg_statusline },
    BufferLineErrorDiagnostic = { fg = t.error, bg = t.bg_dark },
    BufferLineErrorDiagnosticSelected = { fg = t.error, bg = t.bg },
    BufferLineErrorDiagnosticVisible = { fg = t.error, bg = t.bg_statusline },
    BufferLineWarning = { fg = t.warn, bg = t.bg_dark },
    BufferLineWarningSelected = { fg = t.warn, bg = t.bg },
    BufferLineWarningVisible = { fg = t.warn, bg = t.bg_statusline },
    BufferLineWarningDiagnostic = { fg = t.warn, bg = t.bg_dark },
    BufferLineWarningDiagnosticSelected = { fg = t.warn, bg = t.bg },
    BufferLineInfoDiagnostic = { fg = t.info, bg = t.bg_dark },
    BufferLineInfoDiagnosticSelected = { fg = t.info, bg = t.bg },
    BufferLineHintDiagnostic = { fg = t.hint, bg = t.bg_dark },
    BufferLineHintDiagnosticSelected = { fg = t.hint, bg = t.bg },
    BufferLineSeparator = { fg = t.border, bg = t.bg_dark },
    BufferLineSeparatorSelected = { fg = t.border, bg = t.bg },
    BufferLineSeparatorVisible = { fg = t.border, bg = t.bg_statusline },
    BufferLineCloseButton = { fg = t.fg_gutter, bg = t.bg_dark },
    BufferLineCloseButtonSelected = { fg = t.red, bg = t.bg },
    BufferLineCloseButtonVisible = { fg = t.fg_gutter, bg = t.bg_statusline },
    BufferLinePick = { fg = t.gold, bg = t.bg_dark, bold = true },
    BufferLinePickSelected = { fg = t.gold, bg = t.bg, bold = true },
    BufferLinePickVisible = { fg = t.gold, bg = t.bg_statusline, bold = true },
    BufferLineNumbers = { fg = t.fg_gutter, bg = t.bg_dark },
    BufferLineNumbersSelected = { fg = t.green, bg = t.bg, bold = true },
    BufferLineNumbersVisible = { fg = t.fg_dim, bg = t.bg_statusline },
    BufferLineGroupLabel = { fg = t.bg, bg = t.green, bold = true },
    BufferLineGroupSeparator = { fg = t.green, bg = t.bg_dark },
    BufferLineOffsetSeparator = { fg = t.border, bg = t.bg_statusline },
    BufferLineTabSeparatorSelected = { fg = t.green },
    BufferLineTruncMarker = { fg = t.fg_gutter, bg = t.bg_dark },
  }
end

return M
