local M = {}

function M.get(t, _opts)
  local bg_inactive = t.bg_dark

  return {
    BufferLineFill = { bg = bg_inactive },
    BufferLineBackground = { fg = t.fg_dim, bg = bg_inactive },
    BufferLineTab = { fg = t.fg_dim, bg = bg_inactive },
    BufferLineTabSelected = { fg = t.green, bg = t.bg, bold = true },
    BufferLineTabClose = { fg = t.fg_gutter, bg = bg_inactive },
    BufferLineTabSeparator = { fg = t.border, bg = bg_inactive },
    BufferLineTabSeparatorSelected = { fg = t.green, bg = t.bg },
    BufferLineBuffer = { fg = t.fg_dim, bg = bg_inactive },
    BufferLineBufferSelected = { fg = t.green, bg = t.bg, bold = true },
    BufferLineBufferVisible = { fg = t.fg, bg = bg_inactive },
    BufferLineIndicatorSelected = { fg = t.green, bg = t.bg },
    BufferLineIndicatorVisible = { fg = t.border, bg = bg_inactive },
    BufferLineModified = { fg = t.warn, bg = bg_inactive },
    BufferLineModifiedSelected = { fg = t.green, bg = t.bg },
    BufferLineModifiedVisible = { fg = t.warn, bg = bg_inactive },
    BufferLineError = { fg = t.error, bg = bg_inactive },
    BufferLineErrorSelected = { fg = t.error, bg = t.bg },
    BufferLineErrorVisible = { fg = t.error, bg = bg_inactive },
    BufferLineErrorDiagnostic = { fg = t.error, bg = bg_inactive },
    BufferLineErrorDiagnosticSelected = { fg = t.error, bg = t.bg },
    BufferLineErrorDiagnosticVisible = { fg = t.error, bg = bg_inactive },
    BufferLineWarning = { fg = t.warn, bg = bg_inactive },
    BufferLineWarningSelected = { fg = t.warn, bg = t.bg },
    BufferLineWarningVisible = { fg = t.warn, bg = bg_inactive },
    BufferLineWarningDiagnostic = { fg = t.warn, bg = bg_inactive },
    BufferLineWarningDiagnosticSelected = { fg = t.warn, bg = t.bg },
    BufferLineInfoDiagnostic = { fg = t.info, bg = bg_inactive },
    BufferLineInfoDiagnosticSelected = { fg = t.info, bg = t.bg },
    BufferLineHintDiagnostic = { fg = t.hint, bg = bg_inactive },
    BufferLineHintDiagnosticSelected = { fg = t.hint, bg = t.bg },
    BufferLineSeparator = { fg = t.border, bg = bg_inactive },
    BufferLineSeparatorSelected = { fg = t.border, bg = t.bg },
    BufferLineSeparatorVisible = { fg = t.border, bg = bg_inactive },
    BufferLineCloseButton = { fg = t.fg_gutter, bg = bg_inactive },
    BufferLineCloseButtonSelected = { fg = t.red, bg = t.bg },
    BufferLineCloseButtonVisible = { fg = t.fg_gutter, bg = bg_inactive },
    BufferLinePick = { fg = t.gold, bg = bg_inactive, bold = true },
    BufferLinePickSelected = { fg = t.gold, bg = t.bg, bold = true },
    BufferLinePickVisible = { fg = t.gold, bg = bg_inactive, bold = true },
    BufferLineNumbers = { fg = t.fg_gutter, bg = bg_inactive },
    BufferLineNumbersSelected = { fg = t.green, bg = t.bg, bold = true },
    BufferLineNumbersVisible = { fg = t.fg_dim, bg = bg_inactive },
    BufferLineGroupLabel = { fg = t.bg, bg = t.green, bold = true },
    BufferLineGroupSeparator = { fg = t.green, bg = bg_inactive },
    BufferLineOffsetSeparator = { fg = t.border, bg = bg_inactive },
    BufferLineTruncMarker = { fg = t.fg_gutter, bg = bg_inactive },
  }
end

return M
