local M = {}

function M.get(t, _opts)
  return {
    -- nvim-cmp
    CmpItemAbbr = { fg = t.fg },
    CmpItemAbbrDeprecated = { fg = t.comment, strikethrough = true },
    CmpItemAbbrMatch = { fg = t.green, bold = true },
    CmpItemAbbrMatchFuzzy = { fg = t.green },
    CmpItemMenu = { fg = t.comment },
    CmpItemSelected = { bg = t.bg_selection },
    CmpItemKind = { fg = t.fg_dim },
    CmpItemKindText = { fg = t.fg },
    CmpItemKindMethod = { fg = t.blue },
    CmpItemKindFunction = { fg = t.blue },
    CmpItemKindConstructor = { fg = t.violet },
    CmpItemKindField = { fg = t.fg },
    CmpItemKindVariable = { fg = t.fg },
    CmpItemKindClass = { fg = t.violet },
    CmpItemKindInterface = { fg = t.violet },
    CmpItemKindModule = { fg = t.fg },
    CmpItemKindProperty = { fg = t.fg },
    CmpItemKindUnit = { fg = t.orange },
    CmpItemKindValue = { fg = t.orange },
    CmpItemKindEnum = { fg = t.violet },
    CmpItemKindKeyword = { fg = t.green },
    CmpItemKindSnippet = { fg = t.violet },
    CmpItemKindColor = { fg = t.gold },
    CmpItemKindFile = { fg = t.blue },
    CmpItemKindReference = { fg = t.teal },
    CmpItemKindFolder = { fg = t.blue },
    CmpItemKindEnumMember = { fg = t.orange },
    CmpItemKindConstant = { fg = t.orange },
    CmpItemKindStruct = { fg = t.violet },
    CmpItemKindEvent = { fg = t.orange },
    CmpItemKindOperator = { fg = t.teal },
    CmpItemKindTypeParameter = { fg = t.violet },
    CmpItemKindCopilot = { fg = t.teal },
    CmpItemKindCodeium = { fg = t.teal },
    CmpItemKindTabNine = { fg = t.teal },
    CmpDocumentation = { fg = t.fg, bg = t.bg },
    CmpDocumentationBorder = { fg = t.border, bg = t.bg },
    CmpGhostText = { fg = t.comment },

    -- blink.cmp
    BlinkCmpMenu = { fg = t.fg, bg = t.bg },
    BlinkCmpMenuBorder = { fg = t.fg_dim, bg = t.bg },
    BlinkCmpMenuSelection = { fg = t.bg, bg = t.bg_visual },
    BlinkCmpScrollBarThumb = { bg = t.fg_gutter },
    BlinkCmpScrollBarGutter = { bg = t.bg_dark },
    BlinkCmpLabel = { fg = t.fg },
    BlinkCmpLabelDeprecated = { fg = t.comment, strikethrough = true },
    BlinkCmpLabelMatch = { fg = t.green, bold = true },
    BlinkCmpLabelDetail = { fg = t.comment },
    BlinkCmpLabelDescription = { fg = t.comment },
    BlinkCmpKind = { fg = t.fg_dim },
    BlinkCmpKindText = { fg = t.fg },
    BlinkCmpKindMethod = { fg = t.blue },
    BlinkCmpKindFunction = { fg = t.blue },
    BlinkCmpKindConstructor = { fg = t.violet },
    BlinkCmpKindField = { fg = t.fg },
    BlinkCmpKindVariable = { fg = t.fg },
    BlinkCmpKindClass = { fg = t.violet },
    BlinkCmpKindInterface = { fg = t.violet },
    BlinkCmpKindModule = { fg = t.fg },
    BlinkCmpKindProperty = { fg = t.fg },
    BlinkCmpKindUnit = { fg = t.orange },
    BlinkCmpKindValue = { fg = t.orange },
    BlinkCmpKindEnum = { fg = t.violet },
    BlinkCmpKindKeyword = { fg = t.green },
    BlinkCmpKindSnippet = { fg = t.violet },
    BlinkCmpKindColor = { fg = t.gold },
    BlinkCmpKindFile = { fg = t.blue },
    BlinkCmpKindReference = { fg = t.teal },
    BlinkCmpKindFolder = { fg = t.blue },
    BlinkCmpKindEnumMember = { fg = t.orange },
    BlinkCmpKindConstant = { fg = t.orange },
    BlinkCmpKindStruct = { fg = t.violet },
    BlinkCmpKindEvent = { fg = t.orange },
    BlinkCmpKindOperator = { fg = t.teal },
    BlinkCmpKindTypeParameter = { fg = t.violet },
    BlinkCmpKindCopilot = { fg = t.teal },
    BlinkCmpDoc = { fg = t.fg, bg = t.bg },
    BlinkCmpDocBorder = { fg = t.border, bg = t.bg },
    BlinkCmpDocSeparator = { fg = t.border },
    BlinkCmpDocCursorLine = { bg = t.bg_selection },
    BlinkCmpSignatureHelp = { fg = t.fg, bg = t.bg },
    BlinkCmpSignatureHelpBorder = { fg = t.border, bg = t.bg },
    BlinkCmpSignatureHelpActiveParameter = { fg = t.green, underline = true },
    BlinkCmpGhostText = { fg = t.comment },
  }
end

return M
