local M = {}

function M.get(t, _opts)
  return {
    LazyNormal = { fg = t.fg, bg = t.bg },
    LazyBorder = { link = "FloatBorder" },
    LazyButton = { fg = t.fg, bg = t.bg_selection },
    LazyButtonActive = { fg = t.bg, bg = t.green, bold = true },
    LazyComment = { link = "Comment" },
    LazyCommit = { fg = t.teal },
    LazyCommitIssue = { fg = t.orange },
    LazyCommitType = { fg = t.green },
    LazyCommitScope = { fg = t.blue },
    LazyDir = { fg = t.blue },
    LazyH1 = { fg = t.bg, bg = t.green, bold = true },
    LazyH2 = { fg = t.green, bold = true },
    LazyHandler = { fg = t.teal },
    LazyHandlerCmd = { link = "LazyHandler" },
    LazyHandlerEvent = { link = "LazyHandler" },
    LazyHandlerFt = { link = "LazyHandler" },
    LazyHandlerKeys = { link = "LazyHandler" },
    LazyHandlerPlugin = { link = "LazyHandler" },
    LazyHandlerRuntime = { link = "LazyHandler" },
    LazyHandlerSource = { link = "LazyHandler" },
    LazyHandlerStart = { link = "LazyHandler" },
    LazyItalic = { italic = true },
    LazyLocal = { fg = t.orange },
    LazyNoCond = { fg = t.comment },
    LazyNonExistent = { fg = t.comment, italic = true },
    LazyOk = { fg = t.ok },
    LazyProp = { fg = t.fg_dim },
    LazyProgressDone = { fg = t.green, bold = true },
    LazyProgressTodo = { fg = t.comment },
    LazyReasonCmd = { fg = t.teal },
    LazyReasonEvent = { fg = t.gold },
    LazyReasonFt = { fg = t.blue },
    LazyReasonImport = { fg = t.violet },
    LazyReasonKeys = { fg = t.orange },
    LazyReasonPlugin = { fg = t.green },
    LazyReasonRuntime = { fg = t.teal },
    LazyReasonSource = { fg = t.blue },
    LazyReasonStart = { fg = t.green },
    LazySpecial = { fg = t.green },
    LazyTaskError = { fg = t.error },
    LazyTaskOutput = { fg = t.fg },
    LazyUrl = { fg = t.teal, underline = true },
    LazyValue = { fg = t.orange },
  }
end

return M
