local M = {}

function M.get(t, _opts)
  return {
    -- nvim-navic
    NavicIconsFile = { fg = t.blue },
    NavicIconsModule = { fg = t.fg },
    NavicIconsNamespace = { fg = t.fg },
    NavicIconsPackage = { fg = t.fg },
    NavicIconsClass = { fg = t.violet },
    NavicIconsMethod = { fg = t.blue },
    NavicIconsProperty = { fg = t.fg },
    NavicIconsField = { fg = t.fg },
    NavicIconsConstructor = { fg = t.violet },
    NavicIconsEnum = { fg = t.violet },
    NavicIconsInterface = { fg = t.violet },
    NavicIconsFunction = { fg = t.blue },
    NavicIconsVariable = { fg = t.fg },
    NavicIconsConstant = { fg = t.orange },
    NavicIconsString = { fg = t.gold },
    NavicIconsNumber = { fg = t.orange },
    NavicIconsBoolean = { fg = t.orange },
    NavicIconsArray = { fg = t.orange },
    NavicIconsObject = { fg = t.orange },
    NavicIconsKey = { fg = t.green },
    NavicIconsNull = { fg = t.comment },
    NavicIconsEnumMember = { fg = t.orange },
    NavicIconsStruct = { fg = t.violet },
    NavicIconsEvent = { fg = t.orange },
    NavicIconsOperator = { fg = t.teal },
    NavicIconsTypeParameter = { fg = t.violet },
    NavicText = { fg = t.fg_dim },
    NavicSeparator = { fg = t.fg_gutter },

    -- barbecue
    BarbecueNormal = { fg = t.fg, bg = t.bg },
    BarbecueDirname = { fg = t.comment },
    BarbecueBasename = { fg = t.fg },
    BarbecueSeparator = { fg = t.fg_gutter },
    BarbecueModified = { fg = t.warn },
    BarbecueEllipsis = { fg = t.comment },
    BarbecueContext = { fg = t.fg_dim },
    BarbecueContextFile = { fg = t.blue },
    BarbecueContextModule = { fg = t.fg },
    BarbecueContextNamespace = { fg = t.fg },
    BarbecueContextPackage = { fg = t.fg },
    BarbecueContextClass = { fg = t.violet },
    BarbecueContextMethod = { fg = t.blue },
    BarbecueContextProperty = { fg = t.fg },
    BarbecueContextField = { fg = t.fg },
    BarbecueContextConstructor = { fg = t.violet },
    BarbecueContextEnum = { fg = t.violet },
    BarbecueContextInterface = { fg = t.violet },
    BarbecueContextFunction = { fg = t.blue },
    BarbecueContextVariable = { fg = t.fg },
    BarbecueContextConstant = { fg = t.orange },
    BarbecueContextString = { fg = t.gold },
    BarbecueContextNumber = { fg = t.orange },
    BarbecueContextBoolean = { fg = t.orange },
    BarbecueContextArray = { fg = t.orange },
    BarbecueContextObject = { fg = t.orange },
    BarbecueContextKey = { fg = t.green },
    BarbecueContextNull = { fg = t.comment },
    BarbecueContextEnumMember = { fg = t.orange },
    BarbecueContextStruct = { fg = t.violet },
    BarbecueContextEvent = { fg = t.orange },
    BarbecueContextOperator = { fg = t.teal },
    BarbecueContextTypeParameter = { fg = t.violet },
  }
end

return M
