# zero.nvim — Light
# https://github.com/your-username/zero.nvim

[colors.primary]
background = "#f4f5f7"
foreground = "#242731"

[colors.cursor]
text   = "#f4f5f7"
cursor = "#0c8045"

[colors.vi_mode_cursor]
text   = "#f4f5f7"
cursor = "#0c8045"

[colors.search.matches]
foreground = "#f4f5f7"
background = "#7d6a00"

[colors.search.focused_match]
foreground = "#f4f5f7"
background = "#ad520f"

[colors.normal]
black   = "#d8dce3"
red     = "#d61f3a"
green   = "#0c8045"
yellow  = "#7d6a00"
blue    = "#1d6fd0"
magenta = "#7138df"
cyan    = "#0b766c"
white   = "#636b78"

[colors.bright]
black   = "#9ba2ad"
red     = "#bf1731"
green   = "#0b713b"
yellow  = "#6d5c00"
blue    = "#1a61b9"
magenta = "#602cc7"
cyan    = "#096960"
white   = "#242731"
